### ISSUE TITLE
How to install the driver to ESP8266

### ISSUE THREAD

**Issue by yogeshmr** [wdim0/esp8266_with_KeDei_lcd_module#2]
Hi, I am using NodeMCU 1.0 having ESP-12E. How to program the "esp8266_with_KeDei_lcd_module" driver files to the NodeMCU? I currently use Arduino for programming the ESP8266. What environment does the "esp8266_with_KeDei_lcd_module" driver files and user code is intended for programming to ESP8266?

**Comment by wdim0** [comment]
Hi yogeshmr,

sorry, I'm not using Arduino so I cannot tell. I'm using Espressif's NON-OS / RTOS SDK directly. But anyway, it should be easy, since everything is ESP8266 based, am I right?

Anyway, this repo "esp8266_with_KeDei_lcd_module" is just about the hack of KeDei module. If you're looking for the driver itself, please see my "esp8266_fast_lcd_driver_hspi" repo on GitHub.

I would start with downloading the files of "esp8266_fast_lcd_driver_hspi" repo and putting them next to your code, include .h files and try to compile. You'll probably get a few errors because of RTOS - Arduino differences, but it shouldn't be difficult to correct it. If you can wait for a couple of days (max weeks), I'm going to update the "esp8266_fast_lcd_driver_hspi" to NON-OS SDK version, because RTOS SDK is in almost a year delay behind the NON-OS (WiFi Enterprise is completely missing etc...) so I'm abandoning RTOS SDK.

And one more thing - if you're interested specially in KeDei 3.5'' LCD display connected to ESP8266, please be sure that it's module version 4.0 and you do the hack, otherwise it will not work!

Martin

**Comment by yogeshmr** [comment]
Hi Martin,

I am sorry that I have posted this question on "esp8266_with_KeDei_lcd_module" instead of "esp8266_fast_lcd_driver_hspi" repo. I was intending to refer to the "esp8266_fast_lcd_driver_hspi" repo.

Could you please tell how to use the NON-OS SDK on NodeMCU? I downloaded the NON-OS SDK v2.0.0 today and just looked at the files but do not know how to integrate that with your driver files or with the driver files by MetalPhreak in https://github.com/MetalPhreak/ESP8266_SPI_Driver

Currently I am trying to use MetalPhreak's .h and .c files with Arduino but facing invalid library issue. I have to continue looking into it.....

W.r.t the display, I am trying to hack 3.5inch RPi Display 480*320: https://www.aliexpress.com/item/Rasberry-pi-Raspberry-Pi-2-LCD-3-5-inch-TFT-touch-screen-Display-kit-RPI-Touch/32417782639.html. It has two 74HC4094 shift registers, and on each of 74HC4040 counter and 74HC04 inverter ICs.

This display implements the counter and inverters given in your KeDei hack but slightly different such as counter ouput Q3 is used and it feeds directly to the strobe input of the two shift registers (unlike from Q2 and through an inverter in your hack). I think this should not matter as both perform the same action but not as elegantly as in your hack. I do not understand why they have two shift registers, probably one is unused as given in your hack.

**Comment by wdim0** [comment]
Hi,

ok, I understand. I've just installed Arduino IDE, installed the "Generic ESP8266 Module" board and played a little bit with it. Conclusion: it should be possible to use my LCD driver, but it's more work than I expected (many of ESP8266's native includes from the NON-OS SDK would have to be added directly to your sketch directory and edited to make it compatible with Arduino compile environment / or changed the definitions to use Arduino equivalents). Maybe I'll get to it sometime (I should, because the Arduino community is huge), but for now, I have to work on other things.

Anyway ... there is a way for you. I'll describe you my development SW and HW environment and then give you some suggestions where to start: 

- As a development IDE, I'm using Eclipse on Win 7 + Espressif's NON-OS SDK. There's a nice installation guide here (big thanks to Mikhail Grigorev / CHERTS):
http://www.esp8266.com/viewtopic.php?t=820
If you follow the steps correctly, you have everything you need and everything works right out of the box. I've chosen this way because this gives me possibility to use Espressif's latest SDK, gives me access to all the Espressif's SDK functions, better way of control over the ESP8266 chip and it doesn't introduce any intermediate layer which Arduino is probably using to "bend" Arduino's IDE to ESP8266 chip => I guess, the code will be faster here and there.

- I've ESP-07 board connected using "FTDI FT232RL USB to TTL Serial Converter" - search eBay to get one, it's very cheap. Again, I've chosen this minimalistic approach to be on as low level as possibe (lower is only to get the ESP8266 chip alone, create my own PCB board and solder the chip).

=> if you love to dig deeper into the coding, I recommend to switch to Eclipse + Espressif's NON-OS SDK. Yes, it's more complicated than Arduino, but the benefit is bigger / deeper control of everything. And I guess (from what I've googled), that after you compile the program and you get the .bin files, you can use "NodeMCU Firmware Programmer" to flash it to your NodeMCU.

Soon, I'll update my "esp8266_fast_lcd_driver_hspi" repo to use NON-OS (it's for RTOS SDK now).

Martin

**Comment by wdim0** [comment]
BTW: because KeDei doesn't keep the backward compatibility, every "version" of their module is different and they doesn't publish any documentation (at least in English I was not able to google anything) => I recommend to don't use the KeDei hack / KeDei displays. There's better way! There's a LCD module that directly exposes the ILI9488 with no unnecessary intermediate shift registers. This means that we can have the "4-wire 8-bit data serial interface" to ILI9488 without any hacking (we can access pins IM2:0 and set this mode directly). Also, the company that sells the displays seems to take completely different approach - they publish as many info and documentation as possible. Definitely better approach to business than KeDei! And the price is more or less similar. You can find the displays here:
http://www.buydisplay.com/default/serial-spi-3-5-inch-tft-lcd-module-in-320x480-optl-touchscreen-ili9488
or on eBay, as always :)

**Comment by yogeshmr** [comment]
Hi Martin,

Thanks for explaining the set up! So, I have to keep using the "esp8266_fast_lcd_driver_hspi" driver files with Eclipse + RTOS SDK until you update the repo for NON-OS SDK right? Do RTOS SDK v1.5.0 (which seems to be the latest) is ok?

Thanks,
Yogesh

**Comment by wdim0** [comment]
Hi Yogesh,

yes, exactly. The RTOS 1.5.0 is the latest (at the moment) and it is ok. But ... if you need WiFi enterprise functions, it's still missing (NON-OS SDK has it for several updates. I've asked Espressif a few months ago and they confirmed, that they will add these functions to RTOS, but it was a big disappointment to me when realizing, that the "new" 1.5.0. still doesn't have it (I need it for my project)).
I'll try to update my repo this weekend and publish RTOS 1.5.0. + NON-OS 2.0.0. + "Unofficial Development Kit for Espressif ESP8266" (by Mikhail Grigorev) 100% compatible versions.

See you

Martin

**Comment by yogeshmr** [comment]
Hi Martin,

I got the eclipse set up in my Windows 7 machine as explained by CHERTS.
When I try to build your "esp8266_fast_lcd_driver_hspi" code, I get below error:

13:29:52 **** Build of configuration Default for project esp8266_fast_lcd_driver_hspi ****
mingw32-make.exe -f C:/Users/home/eclipse/workspace/esp8266_fast_lcd_driver_hspi/Makefile all 
CC driver/gpio.c
CC driver/wlcd.c
CC wfof/wfof.c
CC user/user_main.c
AR build/app_app.a
==== LD build/app.out1 for slot 1 ============================================
c:/espressif/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/5.2.0/../../../../xtensa-lx106-elf/bin/ld.exe: build/app.out1 section `.text' will not fit in region `iram1_0_seg'
c:/Espressif/ESP8266_RTOS_SDK/lib\libmain.a(app_main.o): In function `flash_data_check':
(.irom0.text+0x550): undefined reference to `user_rf_cal_sector_set'
c:/Espressif/ESP8266_RTOS_SDK/lib\libmain.a(app_main.o): In function `flash_data_check':
(.irom0.text+0x631): undefined reference to `user_rf_cal_sector_set'
collect2.exe: error: ld returned 1 exit status
C:/Users/home/eclipse/workspace/esp8266_fast_lcd_driver_hspi/Makefile:220: recipe for target 'build/app.out1' failed
mingw32-make.exe: *** [build/app.out1] Error 1

13:30:03 Build Finished (took 10s.480ms)

Could you please let me know the fix for this?

**Comment by yogeshmr** [comment]
Hi Martin,

I tried few steps but in vain:

1) Added the code for uint32 ICACHE_FLASH_ATTR user_rf_cal_sector_set(void) to user_main.c (borrowed from the hello world program).

2) Added the below include files to user_main.c and added "C:/Espressif/ESP8266_SDK/include" to the project's "Paths and Symbols". (I confirmed the below .h files are present in this include path). 
#include <osapi.h>
#include <os_type.h>
#include "user_config.h"



I get below error message now: (Which says that the .h files above could not be located by the compiler)

15:15:12 **** Build of configuration Default for project esp8266_fast_lcd_driver_hspi ****
mingw32-make.exe -f C:/Users/home/eclipse/workspace/esp8266_fast_lcd_driver_hspi/Makefile all 
CC driver/gpio.c
CC driver/wlcd.c
CC wfof/wfof.c
CC user/user_main.c
user/user_main.c:13:19: fatal error: osapi.h: No such file or directory
compilation terminated.
mingw32-make.exe: *** [build/user/user_main.o] Error 1
C:/Users/home/eclipse/workspace/esp8266_fast_lcd_driver_hspi/Makefile:318: recipe for target 'build/user/user_main.o' failed

15:15:19 Build Finished (took 7s.711ms)

Thanks,
Yogesh

**Comment by wdim0** [comment]
Hi Yogesh,

check my "esp8266_fast_lcd_driver_hspi" repo. I've just published new version.
See you

Martin

**Comment by yogeshmr** [comment]
Hi Martin,

I m trying the programs...
First with the RTOS build, I got couple of .h files linkage issues which I solved by adding "driver/" prefix the .h files in the include commands.

I further get struck with below error:

20:11:36 **** Build of configuration Default for project WLCD_for_RTOS_(tested_with_1_5_0) ****
mingw32-make.exe -f C:/Users/home/eclipse/workspace/WLCD_for_RTOS_(tested_with_1_5_0)/Makefile all 
CC wfof/wfof.c
CC driver/gpio.c
CC driver/wlcd.c
CC user/user_main.c
AR build/app_app.a
LD build/app.out
c:/espressif/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/5.2.0/../../../../xtensa-lx106-elf/bin/ld.exe: build/app.out section `.text' will not fit in region `iram1_0_seg'
build/app_app.a(wlcd.o): In function `wlcd_read':
C:\Users\home\eclipse\workspace\WLCD_for_RTOS_(tested_with_1_5_0)/driver/wlcd.c:620: undefined reference to `os_free'
build/app_app.a(wlcd.o): In function `wlcd_init':
C:\Users\home\eclipse\workspace\WLCD_for_RTOS_(tested_with_1_5_0)/driver/wlcd.c:1031: undefined reference to `os_free'
collect2.exe: error: ld returned 1 exit status
../common_rtos.mk:230: recipe for target 'build/app.out' failed
mingw32-make.exe: *** [build/app.out] Error 1

Thanks, 
yogesh

**Comment by yogeshmr** [comment]
Hi Martin,

W.r.t the NONOS build, again after adding  "driver/" prefix the .h files in the include commands and then additionally borrowing the espmissingincludes.h file from an example program, I get struck with below error:

20:35:24 **** Build of configuration Default for project WLCD_for_NONOS_(tested_with_2_0_0) ****
mingw32-make.exe -f C:/Users/home/eclipse/workspace/WLCD_for_NONOS_(tested_with_2_0_0)/Makefile all 
CC wfof/wfof.c
CC driver/wlcd.c
In file included from c:/Espressif/ESP8266_SDK/include/ets_sys.h:12:0,
                 from include/driver/espmissingincludes.h:6,
                 from driver/wlcd.c:82:
driver/wlcd.c: In function 'wlcd_init':
driver/wlcd.c:726:41: error: 'FUNC_HSPID_MOSI' undeclared (first use in this function)
  PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTCK_U, FUNC_HSPID_MOSI); //LCD_MOSI
                                         ^
c:/Espressif/ESP8266_SDK/include/eagle_soc.h:50:98: note: in definition of macro 'WRITE_PERI_REG'
 #define WRITE_PERI_REG(addr, val) (*((volatile uint32_t *)ETS_UNCACHED_ADDR(addr))) = (uint32_t)(val)
                                                                                                  ^
driver/wlcd.c:726:2: note: in expansion of macro 'PIN_FUNC_SELECT'
  PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTCK_U, FUNC_HSPID_MOSI); //LCD_MOSI
  ^
driver/wlcd.c:726:41: note: each undeclared identifier is reported only once for each function it appears in
  PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTCK_U, FUNC_HSPID_MOSI); //LCD_MOSI
                                         ^
c:/Espressif/ESP8266_SDK/include/eagle_soc.h:50:98: note: in definition of macro 'WRITE_PERI_REG'
 #define WRITE_PERI_REG(addr, val) (*((volatile uint32_t *)ETS_UNCACHED_ADDR(addr))) = (uint32_t)(val)
                                                                                                  ^
driver/wlcd.c:726:2: note: in expansion of macro 'PIN_FUNC_SELECT'
  PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTCK_U, FUNC_HSPID_MOSI); //LCD_MOSI
  ^
driver/wlcd.c:727:41: error: 'FUNC_HSPIQ_MISO' undeclared (first use in this function)
  PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTDI_U, FUNC_HSPIQ_MISO); //LCD_MISO
                                         ^
c:/Espressif/ESP8266_SDK/include/eagle_soc.h:50:98: note: in definition of macro 'WRITE_PERI_REG'
 #define WRITE_PERI_REG(addr, val) (*((volatile uint32_t *)ETS_UNCACHED_ADDR(addr))) = (uint32_t)(val)
                                                                                                  ^
driver/wlcd.c:727:2: note: in expansion of macro 'PIN_FUNC_SELECT'
  PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTDI_U, FUNC_HSPIQ_MISO); //LCD_MISO
  ^
driver/wlcd.c:728:41: error: 'FUNC_HSPI_CLK' undeclared (first use in this function)
  PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTMS_U, FUNC_HSPI_CLK); //LCD_CLK
                                         ^
c:/Espressif/ESP8266_SDK/include/eagle_soc.h:50:98: note: in definition of macro 'WRITE_PERI_REG'
 #define WRITE_PERI_REG(addr, val) (*((volatile uint32_t *)ETS_UNCACHED_ADDR(addr))) = (uint32_t)(val)
                                                                                                  ^
driver/wlcd.c:728:2: note: in expansion of macro 'PIN_FUNC_SELECT'
  PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTMS_U, FUNC_HSPI_CLK); //LCD_CLK
  ^
../common_nonos.mk:351: recipe for target 'build/driver/wlcd.o' failed
mingw32-make.exe: *** [build/driver/wlcd.o] Error 1

20:35:27 Build Finished (took 2s.80ms)

Thanks,
Yogesh

**Comment by wdim0** [comment]
Hi,

along with the new version, I've added instructions how to install and compile - scroll down on this page:
https://github.com/wdim0/esp8266_fast_lcd_driver_hspi
It seems you didn't do the step 5]

BTW .. I've forgot to copy the espmissingincludes.h into the "modified_NONOS_SDK_files_(overwrite_original)"  directory .. fixed just now. Thanks.

See you

Martin

**Comment by yogeshmr** [comment]
Hi Martin,

I followed the instructions 1 to 8 (yet to try step 9) at https://github.com/wdim0/esp8266_fast_lcd_driver_hspi and successfully built and flashed the code to ESP8266. 

Thanks a lot!

But the demo didn't play on my screen. This was expected, since mine is a different display. I have to now dig deep in to the display hardware and figure out the changes required for the HSPI interface code.

Anyways, thanks a lot for getting me to this stage!!!

Thanks,
Yogesh M R

**Comment by wdim0** [comment]
Hi Yogesh,

perfect! It's good to know that.
See you and good luck!

Martin

**Comment by wdim0** [comment]
Hi Yogesh, there's new version of esp8266_fast_lcd_driver_hspi. If you still have problems, try to use this version.

Martin
